### ISSUE TITLE
アイディア

### ISSUE THREAD

**Issue by shinji19** [lepus-shinagawa/lepus#1]
https://docs.google.com/spreadsheets/d/14v0DBqsG2siU46CN4gft9paMI29kyP_KYZs-AGLVnaU/edit?usp=sharing

**Comment by shinji19** [comment]
https://docs.google.com/spreadsheets/d/14v0DBqsG2siU46CN4gft9paMI29kyP_KYZs-AGLVnaU/edit?usp=sharing

**Comment by Miki-Ak** [comment]
good

**Comment by Zac-eng** [comment]
Thank You!

**Comment by sunagi** [comment]
Thank You

**Comment by yua-t** [comment]
Thanks😆！

**Comment by shinji19** [comment]
全員招待できたので閉じます 🙏
